"""
Template-based explanation generator.
Replaces Qwen2.5-1.5B for diagnostic explanations.
Zero latency. Zero hallucination. No GPU needed.
"""

RULE_DESCRIPTIONS = {
    "high_bp":       "high blood pressure (≥140/90 mmHg), which is a primary risk factor for preeclampsia and eclampsia",
    "borderline_bp": "borderline blood pressure (130–139/80–89 mmHg), which warrants monitoring",
    "high_sugar":    "elevated blood sugar (≥11 mmol/L), indicating possible gestational diabetes",
    "fast_heart":    "elevated heart rate (≥90 bpm), which can indicate cardiovascular stress",
    "fever":         "fever (≥100.4°F), which may signal infection or inflammation",
    "older_mom":     "advanced maternal age (≥35 years), which is associated with increased obstetric risk",
    "normal_bp":     "normal blood pressure (<120/80 mmHg), a reassuring sign",
    "normal_sugar":  "normal blood sugar (<6.1 mmol/L), a reassuring sign",
    "normal_heart":  "normal resting heart rate (60–80 bpm), a reassuring sign",
    "normal_temp":   "normal body temperature (97–99°F), a reassuring sign",
}

VERDICT_INTRO = {
    "🔴 Likely HIGH risk": "Based on the clinical data provided, this patient shows **high risk** indicators that require prompt medical attention.",
    "🟡 Possibly MID risk":  "Based on the clinical data provided, this patient shows **moderate risk** indicators that warrant close monitoring.",
    "⚪ Uncertain — borderline": "Based on the clinical data provided, this patient shows **borderline risk** indicators that require careful assessment.",
    "🟢 Likely LOW risk":  "Based on the clinical data provided, this patient shows **low risk** indicators. Routine prenatal care is recommended.",
}

def generate_explanation(verdict: str, rules_fired: list, final_cf: float, nn_prob_high: float) -> str:
    """
    Generate a human-readable explanation from the diagnosis result.
    No LLM required.
    """
    lines = []

    # Opening sentence
    lines.append(VERDICT_INTRO.get(verdict, f"The patient is assessed as **{verdict}**."))
    lines.append("")

    # Neural network contribution
    nn_pct = round(nn_prob_high * 100)
    lines.append(f"The neural network assigned a {nn_pct}% probability of high-risk status based on the patient's full vital profile.")
    lines.append("")

    # Expert system rules
    positive_rules = [r for r in rules_fired if not r.startswith("normal_")]
    negative_rules = [r for r in rules_fired if r.startswith("normal_")]

    if positive_rules:
        lines.append("**Risk factors identified:**")
        for rule in positive_rules:
            desc = RULE_DESCRIPTIONS.get(rule, rule)
            lines.append(f"- The patient presents with {desc}.")
        lines.append("")

    if negative_rules:
        lines.append("**Reassuring indicators:**")
        for rule in negative_rules:
            desc = RULE_DESCRIPTIONS.get(rule, rule)
            lines.append(f"- The patient shows {desc}.")
        lines.append("")

    # Final CF summary
    cf_pct = round(abs(final_cf) * 100)
    direction = "for" if final_cf >= 0 else "against"
    lines.append(f"The combined certainty factor is **{final_cf:.2f}** ({cf_pct}% cumulative evidence {direction} high risk).")
    lines.append("")
    lines.append("*This assessment is generated by an automated expert system and is not a substitute for professional medical evaluation.*")

    return "\n".join(lines)
